### ISSUE TITLE
다른 사람 프로필 정보가 보이지 않는 오류

### ISSUE THREAD

**Issue by enyo9rt** [2022-Harmony/NewsCommunity-fFinal#92]
## 🎵 설명
- Why? 
: 다른 사람 프로필 정보가 안 나와요!
<br>

- How?
: 프로필이 본인 프로필인지 체크하는 status를 성공 확인용으로 넣어버린 부분 수정
https://github.com/2022-Harmony/NewsCommunity-fFinal/blob/dc568ce3f1bf0f491aa52fcb36c6d3dce00e3968/static/js/profile_about.js#L66

## ✅ 이슈 만들 때 체크하셨나요?
- [x]  할당 (Assignees)
- [x]  라벨(Labels)
- [x]  프로젝트(Projects)

**Comment by hyunzxn** [comment]
오 이슈 쓸 때 코드를 가져다 쓰는건 어떻게 하셨나요?

**Comment by enyo9rt** [comment]
> 오 이슈 쓸 때 코드를 가져다 쓰는건 어떻게 하셨나요?

![image](https://user-images.githubusercontent.com/101458083/179882127-f0161986-5370-45e7-9c40-182c399ce0dd.png)
한 줄 말고 한번 클릭하고 쉬프트 누른 채로 다른 줄 클릭하면 여러줄 선택됩니당

**Comment by hyunzxn** [comment]
> > 오 이슈 쓸 때 코드를 가져다 쓰는건 어떻게 하셨나요?
> 
> ![image](https://user-images.githubusercontent.com/101458083/179882127-f0161986-5370-45e7-9c40-182c399ce0dd.png) 한 줄 말고 한번 클릭하고 쉬프트 누른 채로 다른 줄 클릭하면 여러줄 선택됩니당

오 감사합니다 ㅋㅋㅋ
